
let a=5.3;
console.log(a);
var b="hii";
console.log(b);
{
    let a=33;
    console.log(a);
}
{
    let a=45;
    console.log(a);

}

const  product= {
   title: "pen",
   offer: 4,
   rating:5,
   name:"pen"
}
console.log(product);


const profile={
    name:"shradda khapara",
    post:195,
    followers:569,
    POST:"entrepreneur",
    following:4.
}
console.log(profile);
console.log(typeof profile["following"]);