
// Arithmatic operater
// let a=7;
// let b=37;
// console.log("a+b=",a+b);
// console.log(a-b);
// console.log(a*b);
// console.log(a/b);


//Unary operator
// let a=9;
// let b=78;
// console.log("a=",a,"b=",b);

// console.log(a++);
// console.log(a);
// console.log(++a);

// if(a%2==0){
//    console.log("even number");
// }else{
//     console.log("odd number");
// }
// for(let i=1;i<=100;i++){
//     console.log(i);
// }
// for(let i=1;i<=100;i++){
// if(i%2===0){
//     console.log(i);
// }
// }


// let gameNum= "50";
// let userNum=prompt("guess the number ");
// while(userNum != gameNum){


// userNum=prompt("guess the number Wrong ");
// }

// console.log("congratulations");


// let gameNum = 25;

// let userNum = prompt("Guess the game number:-");

// while (userNum != gameNum){

// userNum=prompt("You entered wrong number. Guess again: ");

// }

// console.log("congratulations, you entered the right number");



//let str ="pratiksha";

// let specialString=`pratiksha`;
// console.log(specialString);

let obj1={
    cost:13,
    object:"pen",
}
// console.log("cost of",student.object,"is", student.cost);
let object=`cost of  ${obj1.object} is ${obj1.cost}`;
console.log(object);